version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-jrdriving}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: sh -c "pnpm install && pnpm --filter @jrdriving/api start:dev"
    working_dir: /workspace
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL:-mysql://root:secret@db:3306/jrdriving}
      JWT_SECRET: ${JWT_SECRET:-super-secret-key}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/workspace:cached
      - pnpm-store:/workspace/.pnpm-store
      - api-node-modules:/workspace/apps/api/node_modules
      - shared-node-modules:/workspace/packages/shared/node_modules

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: sh -c "pnpm install && pnpm --filter @jrdriving/web dev -- --hostname 0.0.0.0 --port 3000"
    working_dir: /workspace
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api}
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      api:
        condition: service_started
    volumes:
      - .:/workspace:cached
      - pnpm-store:/workspace/.pnpm-store
      - web-node-modules:/workspace/apps/web/node_modules
      - shared-node-modules:/workspace/packages/shared/node_modules

volumes:
  mysql-data:
  pnpm-store:
  api-node-modules:
  web-node-modules:
  shared-node-modules:
